name: neyasis
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  http: ^0.13.0
  stream_transform: ^2.0.0
  dio: ^5.3.2
  flutter_native_splash: ^2.3.2
  easy_localization: ^3.0.3
  flutter_dotenv: 5.1.0
  flavor_config: 1.3.0
  mockito: ^5.4.2
  http_mock_adapter: ^0.6.0
  bloc_test: ^9.1.4


flutter_native_splash:
  color: "#d73b36"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    icon_background_color: "#d73b36"


dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash.png
    - assets/translations/